server:
  port: 8066
spring:
  freemarker:
    cache: false
    allow-request-override: false
    check-template-location: true
    charset: UTF-8
    content-type: text/html
    template-loader-path: classpath:/templates/
    suffix: .ftl
  datasource:
    url: jdbc:mysql://vmobel003.mysql.rds.aliyuncs.com/vmobel
    username: testdb
    password: vmobel2015
    driver-class-name: com.mysql.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 50MB
  mvc:
    static-path-pattern: /static/**
  resources:
    static-locations: classpath:/static/
logging:
  file: ./springboot.log
  level:
    cn.coderss: INFO