server:
  port: 8066
spring:
  freemarker:
    cache: false
    allow-request-override: false
    check-template-location: true
    charset: UTF-8
    content-type: text/html
    template-loader-path: classpath:/templates/
    suffix: .ftl
  datasource:
    primary:
      url: jdbc:mysql://vmobel003.mysql.rds.aliyuncs.com/vmobel
      username: testdb
      password: vmobel2015
      driver-class-name: com.mysql.jdbc.Driver
    secondary:
      url: jdbc:mysql://vmobel003.mysql.rds.aliyuncs.com/vmobel
      username: testdb
      password: vmobel2015
      driver-class-name: com.mysql.jdbc.Driver
    name: primary, secondary
  servlet:
    multipart:
      max-file-size: 50MB
  mvc:
    static-path-pattern: /static/**,/downloads/**
  resources:
    static-locations: classpath:/static/,/downloads/
logging:
  file: ./springboot.log
  level:
    cn.coderss: INFO
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.coderss.jysy.domain
mapper:
  identity: MYSQL
  mappers: cn.coderss.jysy.utility.MyMapper
  not-empty: false
logging:
  level:
    cn.coderss: TRACE